import { useEffect, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, Check, ChevronDown, Menu, Minus, Plus, ShoppingBag, X } from 'lucide-react'
import { naira, products, type Product } from './data'

type CartItem = { productId: string; quantity: number }
type Order = { id: string; date: string; total: number; items: CartItem[] }
type View = 'shop' | 'product' | 'checkout' | 'orders'
const storageKey = 'jfas-cart-v1'

export default function App() {
  const [cart, setCart] = useState<CartItem[]>(() => { try { return JSON.parse(localStorage.getItem(storageKey) || '[]') as CartItem[] } catch { return [] } })
  const [view, setView] = useState<View>('shop')
  const [selected, setSelected] = useState<Product | null>(null)
  const [cartOpen, setCartOpen] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [filter, setFilter] = useState('All pieces')
  const [toast, setToast] = useState('')
  const [email, setEmail] = useState('')
  const [orders, setOrders] = useState<Order[]>(() => { try { return JSON.parse(localStorage.getItem('jfas-orders-v1') || '[]') as Order[] } catch { return [] } })
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(cart)) }, [cart])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2400); return () => clearTimeout(timer) }, [toast])
  const count = cart.reduce((n, item) => n + item.quantity, 0)
  const subtotal = cart.reduce((n, item) => n + (products.find(p => p.id === item.productId)?.price || 0) * item.quantity, 0)
  const visibleProducts = filter === 'All pieces' ? products : products.filter(p => p.category === filter)
  const goShop = () => { setView('shop'); setSelected(null); setCartOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const add = (product: Product, quantity = 1) => { setCart(current => { const line = current.find(i => i.productId === product.id); return line ? current.map(i => i.productId === product.id ? { ...i, quantity: i.quantity + quantity } : i) : [...current, { productId: product.id, quantity }] }); setToast(`${product.name} added to your bag`) }
  const changeQty = (id: string, delta: number) => setCart(current => current.map(i => i.productId === id ? { ...i, quantity: i.quantity + delta } : i).filter(i => i.quantity > 0))
  const openProduct = (product: Product) => { setSelected(product); setView('product'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const finishOrder = () => { if (!email.trim()) { setToast('Enter your email to continue'); return } const order = { id: `JF-${Date.now().toString().slice(-7)}`, date: new Date().toISOString(), total: subtotal, items: cart }; const updated = [order, ...orders]; setOrders(updated); localStorage.setItem('jfas-orders-v1', JSON.stringify(updated)); setCart([]); setView('orders'); setToast('Your order is confirmed') }

  return <>
    <div className="announcement">Complimentary delivery on orders over ₦50,000 <span>·</span> Lagos, Nigeria</div>
    <header className="header">
      <button className="icon-button mobile-menu" aria-label="Open menu" onClick={() => setMobileOpen(!mobileOpen)}><Menu size={20} /></button>
      <nav className={`nav-links ${mobileOpen ? 'open' : ''}`}><button onClick={goShop}>Shop all</button><button onClick={() => { setFilter('Jewelry'); goShop() }}>Jewelry</button><button onClick={() => { setFilter('Bags'); goShop() }}>Bags & more</button><button onClick={() => { setView('orders'); setMobileOpen(false) }}>My orders</button></nav>
      <button className="wordmark" onClick={goShop} aria-label="J-FAS home">J-FAS<span>®</span></button>
      <div className="header-actions"><button className="account-link" onClick={() => setView('orders')}>Account</button><button className="icon-button bag-trigger" aria-label={`Shopping bag, ${count} items`} onClick={() => setCartOpen(true)}><ShoppingBag size={19} /><span>Bag ({count})</span></button></div>
    </header>

    <main>
      {view === 'shop' && <>
        <section className="hero">
          <img className="hero-image" src="https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=2200&q=90" alt="Gold jewelry arranged in soft, warm light" />
          <div className="hero-shade" />
          <div className="hero-copy"><p className="eyebrow light">THE EVERYDAY, ELEVATED</p><h1>Made to be<br />kept close.</h1><p>Jewelry and objects for the way you want to feel.</p><button className="light-button" onClick={() => document.getElementById('shop')?.scrollIntoView({ behavior: 'smooth' })}>Discover the collection <ArrowRight size={16} /></button></div>
          <span className="hero-index">01 — 04</span><a className="scroll-cue" href="#shop"><ArrowDown size={14} /> SCROLL TO EXPLORE</a>
        </section>

        <section className="intro"><p className="eyebrow">A LITTLE MORE YOU</p><p className="intro-line">The pieces you reach for without thinking.<br /><em>And remember wearing.</em></p><span>Thoughtfully chosen. Always in season.</span></section>

        <section className="shop-section" id="shop"><div className="section-heading"><div><p className="eyebrow">THE J-FAS EDIT</p><h2>Find your forever piece.</h2></div><button className="text-link" onClick={() => setFilter('All pieces')}>Shop the collection <ArrowRight size={15} /></button></div>
          <div className="filters">{['All pieces', 'Jewelry', 'Bags', 'Accessories'].map(category => <button className={filter === category ? 'active' : ''} key={category} onClick={() => setFilter(category)}>{category}</button>)}<span className="result-count">{visibleProducts.length} pieces</span></div>
          <div className="product-grid">{visibleProducts.map(product => <ProductCard key={product.id} product={product} onOpen={openProduct} onAdd={() => add(product)} />)}</div>
          {visibleProducts.length === 0 && <p className="empty-state">We’re curating this edit now. Check back soon.</p>}
        </section>
        <section className="editorial"><div className="editorial-image"><img src="https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1100&q=85" alt="A close detail of a gold statement ring" /></div><div className="editorial-copy"><p className="eyebrow">THE ART OF THE EVERYDAY</p><h2>Small details.<br /><em>Lasting feeling.</em></h2><p>For the slow mornings, the last-minute plans, and every version of you in between. Meet pieces made to move with you.</p><button className="dark-button" onClick={() => { setFilter('Jewelry'); document.getElementById('shop')?.scrollIntoView({ behavior: 'smooth' }) }}>Explore jewelry <ArrowRight size={15} /></button></div></section>
        <section className="newsletter"><p className="eyebrow">A NOTE FROM US</p><h2>Good things, occasionally.</h2><p>New pieces, styling notes, and the little things we love. No noise.</p><form onSubmit={e => { e.preventDefault(); setToast('You’re on the list — welcome'); }}><input type="email" required placeholder="Your email address" aria-label="Email address" /><button type="submit">Sign me up <ArrowRight size={14} /></button></form><small>By subscribing, you agree to receive our occasional notes.</small></section>
      </>}
      {view === 'product' && selected && <ProductDetail product={selected} onBack={goShop} onAdd={add} />}
      {view === 'checkout' && <section className="checkout-page"><button className="back-link" onClick={() => setCartOpen(true)}><ArrowLeft size={15} /> Back to bag</button><div className="checkout-layout"><div><p className="eyebrow">ALMOST YOURS</p><h1>Checkout</h1><p className="checkout-note">Sign-in will be connected to Supabase. Enter your email to prepare this demo order.</p><label className="field-label">Email address<input type="email" placeholder="you@example.com" value={email} onChange={e => setEmail(e.target.value)} /></label><div className="checkout-section"><h3>Delivery details</h3><div className="field-grid"><label className="field-label">Full name<input placeholder="Your name" /></label><label className="field-label">Phone number<input placeholder="+234" /></label></div><label className="field-label">Delivery address<input placeholder="Street address, area" /></label><div className="field-grid"><label className="field-label">City<input placeholder="Lagos" /></label><label className="field-label">State<input placeholder="Lagos" /></label></div></div><div className="checkout-section"><h3>Payment</h3><p className="payment-placeholder">Payment options will be available when checkout is connected.</p></div></div><aside className="checkout-summary"><h3>Your order</h3>{cart.map(item => { const p = products.find(v => v.id === item.productId); return p ? <div className="summary-item" key={p.id}><img src={p.image} alt="" /><div>{p.name}<small>Qty {item.quantity}</small></div><span>{naira(p.price * item.quantity)}</span></div> : null })}<div className="summary-total"><span>Subtotal</span><b>{naira(subtotal)}</b></div><div className="summary-total muted"><span>Delivery</span><span>Calculated after address</span></div><button className="dark-button full" onClick={finishOrder}>Place demo order <ArrowRight size={15} /></button><small className="secure-note">Your final total and order are verified by our server at checkout.</small></aside></div></section>}
      {view === 'orders' && <section className="orders-page"><p className="eyebrow">YOUR J-FAS</p><h1>Order history</h1><p className="checkout-note">Sign in with Google to view orders linked to your account.</p>{orders.length ? <div className="order-list">{orders.map(order => <article className="order-card" key={order.id}><div className="order-top"><div><b>Order {order.id}</b><span>{new Date(order.date).toLocaleDateString('en-NG', { dateStyle: 'long' })}</span></div><strong>{naira(order.total)}</strong></div><div className="order-products">{order.items.map(line => { const p = products.find(v => v.id === line.productId); return p ? <span key={p.id}>{p.name} × {line.quantity}</span> : null })}</div><div className="order-status"><Check size={14} /> Order confirmed</div></article>)}</div> : <div className="orders-empty"><div className="empty-bag"><ShoppingBag size={24} /></div><h2>Your story starts here.</h2><p>Once you’ve placed an order, you’ll find it here.</p><button className="dark-button" onClick={goShop}>Explore the collection <ArrowRight size={15} /></button></div>}</section>}
    </main>

    <footer className="footer"><div className="footer-top"><div><button className="wordmark footer-logo" onClick={goShop}>J-FAS<span>®</span></button><p>Pieces to make your own.<br />Lagos, Nigeria.</p></div><div className="footer-links"><div><b>Explore</b><button onClick={goShop}>Shop all</button><button onClick={() => { setFilter('Jewelry'); goShop() }}>Jewelry</button><button onClick={() => { setFilter('Bags'); goShop() }}>Bags & more</button></div><div><b>Help</b><button onClick={() => setView('orders')}>My orders</button><a href="mailto:hello@jfas.ng">Get in touch</a><span>Shipping & returns</span></div><div><b>Follow along</b><a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram ↗</a><span>@jfas.ng</span></div></div></div><div className="footer-bottom"><span>© 2026 J-FAS. Made with intention.</span><span>Privacy · Terms</span><span>LAGOS · NIGERIA</span></div></footer>

    {cartOpen && <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) setCartOpen(false) }}><aside className="cart-drawer"><div className="drawer-head"><div><p className="eyebrow">YOUR SELECTION</p><h2>Your bag <span>({count})</span></h2></div><button className="icon-button" aria-label="Close bag" onClick={() => setCartOpen(false)}><X size={20} /></button></div>{cart.length ? <><div className="cart-lines">{cart.map(item => { const p = products.find(v => v.id === item.productId); return p ? <article className="cart-line" key={p.id}><button className="cart-image" onClick={() => { setCartOpen(false); openProduct(p) }}><img src={p.image} alt={p.name} /></button><div className="cart-line-info"><button className="line-name" onClick={() => { setCartOpen(false); openProduct(p) }}>{p.name}</button><span>{naira(p.price)}</span><div className="qty-control"><button aria-label="Decrease quantity" onClick={() => changeQty(p.id, -1)}><Minus size={12} /></button><span>{item.quantity}</span><button aria-label="Increase quantity" onClick={() => changeQty(p.id, 1)}><Plus size={12} /></button></div></div><button className="remove-line" aria-label={`Remove ${p.name}`} onClick={() => setCart(current => current.filter(i => i.productId !== p.id))}>Remove</button></article> : null })}</div><div className="drawer-bottom"><div className="subtotal-line"><span>Subtotal</span><strong>{naira(subtotal)}</strong></div><p>Delivery and any applicable fees are calculated at checkout.</p><button className="dark-button full" onClick={() => { setCartOpen(false); setView('checkout'); window.scrollTo(0, 0) }}>Continue to checkout <ArrowRight size={15} /></button><button className="continue-shopping" onClick={() => setCartOpen(false)}>Continue shopping</button></div></> : <div className="cart-empty"><div className="empty-bag"><ShoppingBag size={24} /></div><h3>A little room for something lovely.</h3><p>Your bag is waiting for its first piece.</p><button className="dark-button" onClick={() => { setCartOpen(false); goShop() }}>Explore the collection <ArrowRight size={15} /></button></div>}</aside></div>}
    {toast && <div className="toast"><Check size={15} />{toast}</div>}
  </>
}

function ProductCard({ product, onOpen, onAdd }: { product: Product; onOpen: (p: Product) => void; onAdd: () => void }) {
  return <article className="product-card"><button className="product-image" onClick={() => onOpen(product)}><img src={product.image} alt={product.name} loading="lazy" />{product.badge && <span className="badge">{product.badge}</span>}<span className="quick-add">Quick add <Plus size={14} /></span></button><div className="product-meta"><div><span className="product-category">{product.category} · {product.color}</span><button className="product-name" onClick={() => onOpen(product)}>{product.name}</button></div><strong>{naira(product.price)}</strong></div><button className="mobile-add" onClick={onAdd}>Add to bag <Plus size={13} /></button></article>
}

function ProductDetail({ product, onBack, onAdd }: { product: Product; onBack: () => void; onAdd: (p: Product, q?: number) => void }) {
  const [quantity, setQuantity] = useState(1)
  return <section className="detail-page"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Back to collection</button><div className="detail-layout"><div className="detail-photo"><img src={product.image} alt={product.name} /></div><div className="detail-info"><p className="eyebrow">{product.category.toUpperCase()} · {product.color.toUpperCase()}</p><h1>{product.name}</h1><strong className="detail-price">{naira(product.price)}</strong><p className="detail-description">{product.description}</p><p className="detail-delivery">Complimentary delivery on orders over ₦50,000.</p><div className="detail-quantity"><span>Quantity</span><div className="qty-control"><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={12} /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => setQuantity(quantity + 1)}><Plus size={12} /></button></div></div><button className="dark-button full" onClick={() => onAdd(product, quantity)}>Add to bag — {naira(product.price * quantity)} <ShoppingBag size={15} /></button><div className="detail-accordion"><details open><summary>Details <ChevronDown size={14} /></summary><p>Designed to be worn on repeat. Each J-FAS piece is carefully selected for its considered shape and lasting appeal.</p></details><details><summary>Care <ChevronDown size={14} /></summary><p>Keep away from water, perfume, and lotions. Store in a dry place between wears.</p></details><details><summary>Delivery & returns <ChevronDown size={14} /></summary><p>Orders are prepared with care. Delivery options and timing are confirmed at checkout.</p></details></div></div></div><div className="related-heading"><p className="eyebrow">MORE TO LOVE</p><h2>Consider these, too.</h2></div><div className="product-grid related-grid">{products.filter(p => p.id !== product.id).slice(0, 4).map(p => <ProductCard key={p.id} product={p} onOpen={() => { window.scrollTo(0, 0); }} onAdd={() => onAdd(p)} />)}</div></section>
}
